//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetService
    {
        public int AssetServiceID { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
        public string Cost { get; set; }
        public int VendorID { get; set; }
        public int AssetID { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
