//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asset()
        {
            this.Histories = new HashSet<History>();
        }
    
        public int AssetID { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> Warranty { get; set; }
        public Nullable<int> MonthDepreciation { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> AssetServiceID { get; set; }
        public int AssetStatusID { get; set; }
        public Nullable<int> OrderDetailID { get; set; }
        public Nullable<System.DateTime> EndTimeDepreciation { get; set; }
    
        public virtual AssetStatus AssetStatus { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History> Histories { get; set; }
    }
}
