//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public string HistoryID { get; set; }
        public Nullable<System.DateTime> Checkout_Date { get; set; }
        public Nullable<System.DateTime> Checkin_Date { get; set; }
        public string Comment { get; set; }
        public int PersonnelID { get; set; }
        public int AssetID { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual Personnel Personnel { get; set; }
    }
}
