
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class OrderDetail
{

    public int OrderDetailID { get; set; }

    public int Quantity { get; set; }

    public decimal Subtotal { get; set; }

    public decimal Price { get; set; }

    public int AssetID { get; set; }

    public int OrderID { get; set; }



    public virtual Asset Asset { get; set; }

    public virtual Order Order { get; set; }

}

}
