//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderDetail()
        {
            this.Assets = new HashSet<Asset>();
        }
    
        public int OrderDetailID { get; set; }
        public int Quantity { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> QuoteID { get; set; }
        public Nullable<int> VendorID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset> Assets { get; set; }
        public virtual Order Order { get; set; }
        public virtual Quote Quote { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
