//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORequest
    {
        public int AssetRequestID { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public int RequestStatusID { get; set; }
        public Nullable<int> QuoteID { get; set; }
        public Nullable<int> OrderID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public virtual RequestStatus RequestStatus { get; set; }
        public virtual Quote Quote { get; set; }
    }
}
