//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public int QuoteID { get; set; }
        public string Image { get; set; }
        public string ProductName { get; set; }
        public string Brand { get; set; }
        public string CategoryName { get; set; }
        public string Vendor { get; set; }
        public decimal Price { get; set; }
        public int Warranty { get; set; }
        public string Note { get; set; }
        public int PoRequestID { get; set; }
    
        public virtual PoRequest PoRequest { get; set; }
    }
}
