
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Quote
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Quote()
    {

        this.PORequests = new HashSet<PORequest>();

    }


    public int QuoteID { get; set; }

    public string Note { get; set; }

    public string Warranty { get; set; }

    public decimal Price { get; set; }

    public string VendorName { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PORequest> PORequests { get; set; }

}

}
